export const data = [
  {
    "orderid": 10001,
    "cusname": "Abbas Medico",
    "marketadd": "Banani Model Town,Dhaka-123,Bangladesh",
    "orddate": "03/05/2021 13:00",
    "proceed": "Yasir(RSM)",
  },
  {
    "orderid": 10001,
    "cusname": "Abbas Medico",
    "marketadd": "Banani Model Town,Dhaka-123,Bangladesh",
    "orddate": "03/05/2021 13:00",
    "proceed": "Yasir(RSM)",
  },
  {
    "orderid": 10001,
    "cusname": "Abbas Medico",
    "marketadd": "Banani Model Town,Dhaka-123,Bangladesh",
    "orddate": "03/05/2021 13:00",
    "proceed": "Yasir(RSM)",
  },
  {
    "orderid": 10001,
    "cusname": "Abbas Medico",
    "marketadd": "Banani Model Town,Dhaka-123,Bangladesh",
    "orddate": "03/05/2021 13:00",
    "proceed": "Yasir(RSM)",
  },
  {
    "orderid": 10001,
    "cusname": "Abbas Medico",
    "marketadd": "Banani Model Town,Dhaka-123,Bangladesh",
    "orddate": "03/05/2021 13:00",
    "proceed": "Yasir(RSM)",
  },
  {
    "orderid": 10001,
    "cusname": "Abbas Medico",
    "marketadd": "Banani Model Town,Dhaka-123,Bangladesh",
    "orddate": "03/05/2021 13:00",
    "proceed": "Yasir(RSM)",
  },
  {
    "orderid": 10001,
    "cusname": "Abbas Medico",
    "marketadd": "Banani Model Town,Dhaka-123,Bangladesh",
    "orddate": "03/05/2021 13:00",
    "proceed": "Yasir(RSM)",
  },
  {
    "orderid": 10001,
    "cusname": "Abbas Medico",
    "marketadd": "Banani Model Town,Dhaka-123,Bangladesh",
    "orddate": "03/05/2021 13:00",
    "proceed": "Yasir(RSM)",
  },
  {
    "orderid": 10001,
    "cusname": "Abbas Medico",
    "marketadd": "Banani Model Town,Dhaka-123,Bangladesh",
    "orddate": "03/05/2021 13:00",
    "proceed": "Yasir(RSM)",
  },
  {
    "orderid": 10001,
    "cusname": "Abbas Medico",
    "marketadd": "Banani Model Town,Dhaka-123,Bangladesh",
    "orddate": "03/05/2021 13:00",
    "proceed": "Yasir(RSM)",
  },
  {
    "orderid": 10001,
    "cusname": "Abbas Medico",
    "marketadd": "Banani Model Town,Dhaka-123,Bangladesh",
    "orddate": "03/05/2021 13:00",
    "proceed": "Yasir(RSM)",
  },
  {
    "orderid": 10001,
    "cusname": "Abbas Medico",
    "marketadd": "Banani Model Town,Dhaka-123,Bangladesh",
    "orddate": "03/05/2021 13:00",
    "proceed": "Yasir(RSM)",
  },
  {
    "orderid": 10001,
    "cusname": "Abbas Medico",
    "marketadd": "Banani Model Town,Dhaka-123,Bangladesh",
    "orddate": "03/05/2021 13:00",
    "proceed": "Yasir(RSM)",
  },
  {
    "orderid": 10001,
    "cusname": "Abbas Medico",
    "marketadd": "Banani Model Town,Dhaka-123,Bangladesh",
    "orddate": "03/05/2021 13:00",
    "proceed": "Yasir(RSM)",
  },
  {
    "orderid": 10001,
    "cusname": "Abbas Medico",
    "marketadd": "Banani Model Town,Dhaka-123,Bangladesh",
    "orddate": "03/05/2021 13:00",
    "proceed": "Yasir(RSM)",
  },
]




export const stockdata = [
  {
    "sno": 101,
    "prodname": "Aceclofenac. Flexi",
    "prodfor": "Bicozin-I",
    "quan": "52",
  },
  {
    "sno": 101,
    "prodname": "Aceclofenac. Flexi",
    "prodfor": "Bicozin-I",
    "quan": "52",
  },
  {
    "sno": 101,
    "prodname": "Aceclofenac. Flexi",
    "prodfor": "Bicozin-I",
    "quan": "52",
  },
  {
    "sno": 101,
    "prodname": "Aceclofenac. Flexi",
    "prodfor": "Bicozin-I",
    "quan": "52",
  },
  {
    "sno": 101,
    "prodname": "Aceclofenac. Flexi",
    "prodfor": "Bicozin-I",
    "quan": "52",
  },
  {
    "sno": 101,
    "prodname": "Aceclofenac. Flexi",
    "prodfor": "Bicozin-I",
    "quan": "52",
  },
  {
    "sno": 101,
    "prodname": "Aceclofenac. Flexi",
    "prodfor": "Bicozin-I",
    "quan": "52",
  },
  {
    "sno": 101,
    "prodname": "Aceclofenac. Flexi",
    "prodfor": "Bicozin-I",
    "quan": "52",
  },
  {
    "sno": 101,
    "prodname": "Aceclofenac. Flexi",
    "prodfor": "Bicozin-I",
    "quan": "52",
  },
  {
    "sno": 101,
    "prodname": "Aceclofenac. Flexi",
    "prodfor": "Bicozin-I",
    "quan": "52",
  },
  {
    "sno": 101,
    "prodname": "Aceclofenac. Flexi",
    "prodfor": "Bicozin-I",
    "quan": "52",
  },
  {
    "sno": 101,
    "prodname": "Aceclofenac. Flexi",
    "prodfor": "Bicozin-I",
    "quan": "52",
  },
  {
    "sno": 101,
    "prodname": "Aceclofenac. Flexi",
    "prodfor": "Bicozin-I",
    "quan": "52",
  },
  {
    "sno": 101,
    "prodname": "Aceclofenac. Flexi",
    "prodfor": "Bicozin-I",
    "quan": "52",
  },
]