export const directorConstants = {
    GET_SCHEDULE: "GET_SCHEDULE",
    APPROVAL_STATUS_CHANGE: "APPROVAL_STATUS_CHANGE",
    GET_DOCTOR: "GET_DOCTOR",
    GET_CUSTOMER: "GET_CUSTOMER",
    GET_ASSIGNED_TO: "GET_ASSIGNED_TO",
  };
  