export const staticConstants = {
    ALL_NOTIFICATIONS: "ALL_NOTIFICATIONS",
    NEW_NOTIFICATIONS: "NEW_NOTIFICATIONS",
    NOTIFICATION_COUNT: "NOTIFICATION_COUNT",
    NOTIFICATION: "NOTIFICATION",
}